# Certificate for zita.localtest.me using cert-manager + step-issuer
# Namespace must exist: zitadel
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zita-cert
  namespace: zitadel
spec:
  secretName: zita-tls
  dnsNames:
    - zita.localtest.me
  issuerRef:
    group: certmanager.step.sm
    kind: StepClusterIssuer
    name: step-ca-cluster-issuer
